import { parseLevel } from './format';

// Level 1: Die Wiese. Leichte Hindernisse, kleine Lücken, am Ende die Ziel-Fahne.
export default parseLevel('Die Wiese', `
..................................................................................................................................
..................................................................................................................................
..................................................................................................................................
..................................................................................................................................
..................................................................................................................................
..................................................................................................................................
..........................C........t.................##......................C...........................GGG......................
...S...t..#...t........t..C....GGGGGGGGG........P...####..t..PPP.....t...C...C............t.....HH..t.GGGDDDGGG.......t...Z...t...
GGGGGGGGGGGGGGGGG..GGGGGGGGGGGGDDDDDDDDDGG...GGGGGGGGGGGGGGG.....GGGGGGGGGGGGGGGG..GG..GGGGGGGGGGGGGGGDDDDDDDDDG..GGGGGGGGGGGGGGGG
DDDDDDDDDDDDDDDDD..DDDDDDDDDDDDDDDDDDDDDDD...DDDDDDDDDDDDDDD.....DDDDDDDDDDDDDDDD..DD..DDDDDDDDDDDDDDDDDDDDDDDDD..DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDD..DDDDDDDDDDDDDDDDDDDDDDD...DDDDDDDDDDDDDDD.....DDDDDDDDDDDDDDDD..DD..DDDDDDDDDDDDDDDDDDDDDDDDD..DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDD..DDDDDDDDDDDDDDDDDDDDDDD...DDDDDDDDDDDDDDD.....DDDDDDDDDDDDDDDD..DD..DDDDDDDDDDDDDDDDDDDDDDDDD..DDDDDDDDDDDDDDDD
`);
